name: kitchen
channels:
  - conda-forge  # Prefer community-maintained packages first
  - fastai       # Added for opencv-python-headless (if necessary)
  - defaults     # Default channel as fallback
dependencies:
  - python=3.10
  - numpy=1.26.4
  - scipy
  - qpsolvers
  - albumentations
  - imageio[ffmpeg]
  - ipykernel
  - ipympl
  - matplotlib
  - tabulate
  - cython
  - librealsense
  - fastai::opencv-python-headless=4.10.0.84
  - conda-forge::colmap
  - nvidia/label/cuda-11.8.0::cuda-toolkit
  - nvidia/label/cuda-11.8.0::cuda-nvcc
  - pip
  - pip:
    - --index-url https://download.pytorch.org/whl/cu118
    - torch==2.1.2+cu118
    - torchvision==0.16.2+cu118